version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: garden-shop-db
    environment:
      POSTGRES_DB: garden-shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: predators
    ports:
      - "5432:5432"
    networks:
      - garden-net
    restart: always


  garden-shop:
    image: garden-shop
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/garden-shop
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: predators
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - garden-net
    restart: always

networks:
  garden-net:
    driver: bridge
